"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { motion, useReducedMotion } from "framer-motion";
import { Activity, ArrowRight, BadgeCheck, BrainCircuit, CircleAlert, FileText, Fingerprint, GitBranch, Mail, Radar, RefreshCw, ShieldCheck, Sparkles, type LucideIcon } from "lucide-react";
import { useAuth } from "@/components/auth-provider";
import { Button } from "@/components/ui/button";
import { buildGenomeSnapshot, emptyGenomeSnapshot } from "@/features/identity-intelligence/adapter";
import { IntelligenceApiError, loadGenomeIntelligence } from "@/features/identity-intelligence/api";
import { buildGenomeHologramSignals, genomeHealth } from "@/features/identity-intelligence/hologram-signals";
import { browserGenomeStore } from "@/features/identity-intelligence/session";
import type { GenomeSnapshot } from "@/features/identity-intelligence/types";
import { knowledgeRepository } from "@/features/identity-knowledge/knowledge-repository";

type SystemState = "healthy" | "awaiting";

export function CommandCenterDashboard() {
  const { user } = useAuth();
  const reduceMotion = useReducedMotion();
  const [snapshot, setSnapshot] = useState<GenomeSnapshot>(() => emptyGenomeSnapshot());
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [attempt, setAttempt] = useState(0);

  useEffect(() => {
    let active = true;
    async function load() {
      if (!user?.uid) { if (active) setLoading(false); return; }
      const session = browserGenomeStore.load(user.uid);
      if (!session) { if (active) { setSnapshot(emptyGenomeSnapshot()); setError(null); setLoading(false); } return; }
      try {
        const payload = await loadGenomeIntelligence(session.genomeId);
        const next = await buildGenomeSnapshot(payload, session.sources, knowledgeRepository.load(user.uid));
        if (active) { setSnapshot(next); setError(null); }
      } catch (cause) {
        if (cause instanceof IntelligenceApiError && cause.status === 404) browserGenomeStore.clear(user.uid);
        if (active) { setSnapshot(emptyGenomeSnapshot()); setError("Your current Identity Genome could not be loaded. You can retry or add a consented source."); }
      } finally { if (active) setLoading(false); }
    }
    void load();
    return () => { active = false; };
  }, [attempt, user?.uid]);

  const signals = useMemo(() => buildGenomeHologramSignals(snapshot), [snapshot]);
  const health = genomeHealth(signals);
  const lastSync = snapshot.profile?.updated_at ?? snapshot.latestVersion?.created_at;
  const hasGmail = snapshot.sources.some((source) => source.sourceId === "gmail" && source.status === "ingested");
  const systems: Array<{ label: string; icon: LucideIcon; state: SystemState; detail: string }> = [
    { label: "Identity Genome", icon: Fingerprint, state: snapshot.hasExtractedKnowledge ? "healthy" : "awaiting", detail: snapshot.hasExtractedKnowledge ? "Current version loaded" : "Awaiting consented evidence" },
    { label: "Identity Twin", icon: BrainCircuit, state: snapshot.hasExtractedKnowledge ? "healthy" : "awaiting", detail: snapshot.hasExtractedKnowledge ? "Evidence-bound reasoning ready" : "Requires Genome evidence" },
    { label: "Guardian", icon: ShieldCheck, state: snapshot.hasExtractedKnowledge ? "healthy" : "awaiting", detail: snapshot.insights[0]?.detail ?? "Watching for evidence" },
    { label: "Evidence Engine", icon: Activity, state: snapshot.sourceCount ? "healthy" : "awaiting", detail: snapshot.sourceCount ? `${snapshot.sourceCount} source${snapshot.sourceCount === 1 ? "" : "s"} available` : "No source analyzed" },
    { label: "Reasoning Engine", icon: GitBranch, state: snapshot.hasExtractedKnowledge ? "healthy" : "awaiting", detail: "Deterministic and bounded" },
    { label: "Investigation Engine", icon: Radar, state: "healthy", detail: "Ready for a new artifact" },
    { label: "Certificate Engine", icon: BadgeCheck, state: "awaiting", detail: "Available after an investigation" },
    { label: "Gmail Connector", icon: Mail, state: hasGmail ? "healthy" : "awaiting", detail: hasGmail ? "Consented evidence linked" : "Optional source not connected" },
  ];
  const activity = [...snapshot.timeline.slice(0, 4), ...snapshot.insights.slice(0, 2).map((item) => ({ id: item.id, title: item.title, detail: item.detail, timestamp: item.updatedAt }))];

  if (loading) return <DashboardSkeleton />;
  return <section className="mx-auto max-w-[96rem] px-5 py-8 md:px-8 md:py-10">
    <motion.header initial={reduceMotion ? false : { opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: reduceMotion ? 0 : .35 }} className="flex flex-wrap items-end justify-between gap-5"><div><p className="font-mono text-[11px] tracking-[.17em] text-[#aea3ff]">TRUSTDNA COMMAND CENTER</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white md:text-4xl">Your Identity Intelligence Operating System.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">Live system state is derived from your current Identity Genome. Missing evidence remains visible rather than inferred.</p></div><Button asChild className="h-11 rounded-xl bg-[#8b78f6] text-white hover:bg-[#9c8aff]"><Link href="/investigate">Run investigation <ArrowRight className="size-4" /></Link></Button></motion.header>
    {error && <div role="status" className="mt-6 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-amber-200/15 bg-amber-200/[.06] p-4"><div className="flex gap-3"><CircleAlert aria-hidden="true" className="mt-0.5 size-4 text-amber-200" /><p className="text-xs leading-5 text-amber-50">{error}</p></div><Button type="button" variant="outline" onClick={() => { setLoading(true); setAttempt((value) => value + 1); }} className="border-amber-200/20 bg-transparent text-amber-50 hover:bg-amber-200/[.08] hover:text-white"><RefreshCw className="size-3.5" />Retry</Button></div>}
    <section aria-label="Identity system status" className="mt-7 grid gap-px overflow-hidden rounded-2xl border border-white/[.09] bg-white/[.08] sm:grid-cols-2 xl:grid-cols-6">{[["Identity health", `${health}%`], ["Genome version", snapshot.latestVersion?.version ?? "Awaiting"], ["Evidence sources", String(snapshot.sourceCount)], ["Knowledge objects", String(snapshot.knowledgeObjects.length)], ["Last sync", formatTimestamp(lastSync)], ["Confidence", snapshot.genomeConfidence === undefined ? "Awaiting" : `${snapshot.genomeConfidence}%`]].map(([label, value]) => <StatusMetric key={label} label={label} value={value} />)}</section>
    <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(20rem,.75fr)]"><section className="glass relative overflow-hidden rounded-[1.7rem] border border-white/[.1] p-5 sm:p-6"><div aria-hidden="true" className="absolute -left-20 -top-20 size-64 rounded-full bg-cyan-300/[.08] blur-3xl" /><div className="relative flex items-start justify-between gap-4"><div><p className="font-mono text-[10px] tracking-[.16em] text-cyan-100">GENOME HEALTH</p><h2 className="mt-2 text-xl font-medium text-white">Coverage, confidence, and evidence diversity.</h2><p className="mt-2 text-xs leading-5 text-slate-400">Health visualizes direct-evidence coverage and confidence, not personality.</p></div><div className="grid size-28 place-items-center rounded-full border border-cyan-300/20" style={{ background: `radial-gradient(closest-side, #0a1028 76%, transparent 77% 100%), conic-gradient(#7ee8ff ${health}%, rgba(255,255,255,.08) 0)` }}><span className="font-mono text-xl font-semibold text-cyan-100">{health}%</span></div></div><div className="relative mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{signals.slice(0, 9).map((signal, index) => <motion.div key={signal.id} initial={reduceMotion ? false : { opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: reduceMotion ? 0 : index * .035 }} className="rounded-xl border border-white/[.07] bg-black/[.13] p-3"><p className="font-mono text-[8px] tracking-[.12em] text-slate-500">{signal.label.toUpperCase()}</p><p className="mt-2 text-lg font-semibold text-white">{signal.evidenceCount}</p><p className="mt-1 text-[10px] text-slate-500">{signal.confidence === null ? "Awaiting evidence" : `${Math.round(signal.confidence * 100)}% confidence`}</p></motion.div>)}</div></section><ActivityFeed activity={activity} /></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.05fr)_minmax(20rem,.95fr)]"><section className="glass rounded-[1.7rem] border border-white/[.1] p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-[10px] tracking-[.14em] text-[#c6bfff]">LIVE SYSTEM STATUS</p><h2 className="mt-2 text-lg font-medium text-white">Every module declares its actual state.</h2></div><span className="rounded-full border border-cyan-300/20 bg-cyan-300/[.06] px-2.5 py-1 font-mono text-[8px] tracking-[.12em] text-cyan-100">{systems.filter((system) => system.state === "healthy").length} HEALTHY</span></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{systems.map((system) => <SystemModule key={system.label} {...system} />)}</div></section><SystemMap /></div>
    <section aria-labelledby="quick-actions-heading" className="mt-5"><div className="flex items-end justify-between gap-4"><div><p className="font-mono text-[10px] tracking-[.14em] text-[#c6bfff]">QUICK ACTIONS</p><h2 id="quick-actions-heading" className="mt-2 text-lg font-medium text-white">Advance your Identity Genome deliberately.</h2></div><span className="text-xs text-slate-500">No background polling</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><ActionCard href="/gmail" icon={Mail} title="Connect Gmail" detail="Add consented email evidence" /><ActionCard href="/genome" icon={Fingerprint} title="Add notes" detail="Expand direct knowledge" /><ActionCard href="/investigate" icon={Radar} title="Run investigation" detail="Open a forensic case" /><ActionCard href="/twin" icon={BrainCircuit} title="Open Twin" detail="Ask an evidence-bound question" /></div></section>
  </section>;
}

function StatusMetric({ label, value }: { label: string; value: string }) { return <div className="bg-[#091027]/75 px-4 py-3"><p className="font-mono text-[8px] tracking-[.12em] text-slate-600">{label.toUpperCase()}</p><p className="mt-1 truncate text-sm font-medium text-slate-100">{value}</p></div>; }
function SystemModule({ label, icon: Icon, state, detail }: { label: string; icon: LucideIcon; state: SystemState; detail: string }) { const ready = state === "healthy"; return <article className={`rounded-xl border p-3 ${ready ? "border-cyan-300/20 bg-cyan-300/[.06]" : "border-white/[.08] bg-black/[.12]"}`}><div className="flex items-start gap-3"><Icon aria-hidden="true" className={`mt-0.5 size-4 shrink-0 ${ready ? "text-cyan-100" : "text-slate-500"}`} /><div className="min-w-0"><div className="flex items-center justify-between gap-2"><h3 className="text-xs font-medium text-slate-100">{label}</h3><span className={`font-mono text-[8px] tracking-[.09em] ${ready ? "text-cyan-100" : "text-slate-500"}`}>{ready ? "HEALTHY" : "AWAITING"}</span></div><p className="mt-1 text-[10px] leading-4 text-slate-500">{detail}</p></div></div></article>; }
function ActivityFeed({ activity }: { activity: Array<{ id: string; title: string; detail: string; timestamp?: string }> }) { return <section className="glass rounded-[1.7rem] border border-white/[.1] p-5 sm:p-6"><div className="flex items-center gap-2"><Activity aria-hidden="true" className="size-4 text-cyan-200" /><div><p className="font-mono text-[10px] tracking-[.14em] text-cyan-100">LIVE ACTIVITY STREAM</p><h2 className="mt-1 text-base font-medium text-white">Recorded Genome activity</h2></div></div>{activity.length ? <ol className="mt-6 space-y-4">{activity.map((item, index) => <li key={item.id} className="relative flex gap-3"><span aria-hidden="true" className={`mt-1.5 size-2 shrink-0 rounded-full ${index === 0 ? "bg-cyan-200 shadow-[0_0_10px_#7ee8ff]" : "bg-[#a99bff]"}`} /><div><p className="text-xs text-slate-200">{item.title}</p><p className="mt-1 text-[11px] leading-5 text-slate-500">{item.detail}</p><p className="mt-1 font-mono text-[8px] tracking-[.1em] text-slate-600">{formatTimestamp(item.timestamp)}</p></div></li>)}</ol> : <div className="mt-6 grid min-h-48 place-items-center rounded-2xl border border-dashed border-white/[.1] bg-black/[.12] p-6 text-center"><Sparkles aria-hidden="true" className="size-5 text-slate-600" /><p className="mt-3 text-sm text-slate-300">Awaiting recorded activity</p><p className="mt-2 text-xs leading-5 text-slate-500">Add consented Identity Genome evidence to establish a versioned timeline event.</p></div>}</section>; }
function SystemMap() { const nodes: Array<[LucideIcon, string]> = [[Fingerprint, "Genome"], [BrainCircuit, "Twin"], [ShieldCheck, "Guardian"], [Radar, "Investigate"], [FileText, "Evidence"], [BadgeCheck, "Certificates"]]; return <section className="glass relative overflow-hidden rounded-[1.7rem] border border-white/[.1] p-5 sm:p-6"><div aria-hidden="true" className="absolute -right-20 bottom-0 size-56 rounded-full bg-violet-400/[.08] blur-3xl" /><div className="relative"><p className="font-mono text-[10px] tracking-[.14em] text-[#c6bfff]">SYSTEM MAP</p><h2 className="mt-2 text-lg font-medium text-white">Evidence flows through explicit boundaries.</h2><div className="mt-7 grid gap-3 sm:grid-cols-3">{nodes.map(([Icon, label]) => <div key={label} className="group rounded-xl border border-white/[.08] bg-black/[.12] p-3 transition hover:border-cyan-300/30 hover:bg-cyan-300/[.045]"><Icon aria-hidden="true" className="size-4 text-[#bcb3ff] transition group-hover:text-cyan-100" /><p className="mt-3 text-xs text-slate-200">{label}</p></div>)}</div><p className="mt-5 text-xs leading-5 text-slate-500">The map shows available modules. It does not claim background monitoring or connector activity that is absent from this Genome.</p></div></section>; }
function ActionCard({ href, icon: Icon, title, detail }: { href: string; icon: LucideIcon; title: string; detail: string }) { return <Link href={href} className="group rounded-2xl border border-white/[.08] bg-black/[.12] p-4 transition hover:-translate-y-0.5 hover:border-[#b9adff]/35 hover:bg-white/[.04] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#b9adff]"><Icon aria-hidden="true" className="size-4 text-[#bfb6ff] transition group-hover:text-cyan-100" /><p className="mt-5 text-sm font-medium text-white">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p><span className="mt-4 inline-flex items-center gap-1 text-[11px] text-[#c5bdff]">Open <ArrowRight className="size-3" /></span></Link>; }
function DashboardSkeleton() { return <section aria-label="Loading TrustDNA Command Center" className="mx-auto max-w-[96rem] animate-pulse px-5 py-8 md:px-8 md:py-10"><div className="h-3 w-52 rounded bg-white/[.08]" /><div className="mt-4 h-10 max-w-2xl rounded bg-white/[.08]" /><div className="mt-3 h-5 max-w-3xl rounded bg-white/[.05]" /><div className="mt-8 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><div className="h-[30rem] rounded-[1.7rem] border border-white/[.06] bg-white/[.035]" /><div className="h-[30rem] rounded-[1.7rem] border border-white/[.06] bg-white/[.035]" /></div></section>; }
function formatTimestamp(value: string | undefined): string { if (!value) return "Awaiting first sync"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(date); }
