import { AlertTriangle, Check, Clock3, Fingerprint, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import type { InvestigationResult, Scenario } from "@/features/judge/types";

type CaseFileProps = { result: InvestigationResult; scenario: Scenario };

const labels: Record<string, string> = { case_created: "Sentinel opened case", collecting_evidence: "Evidence collected", dispatching_agents: "Forensic agents dispatched", awaiting_results: "Agent evidence returned", aggregating: "Evidence aggregated", risk_analysis: "Risk Engine assessed confidence", generating_findings: "Case findings generated", generating_certificate: "TrustDNA Certificate generated", closed: "Investigation closed" };

export function CaseFile({ result, scenario }: CaseFileProps) {
  const highRisk = result.investigation.verdict === "impersonation_confirmed";
  const match = Math.round(result.risk.breakdown.weighted_score * 100);
  const agent = result.agents.find((item) => item.agent === "cipher");
  const evidence = agent?.evidence ?? [];
  return <section className="mx-auto w-full max-w-7xl px-5 py-14 md:px-10"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-medium tracking-[.18em] text-[#aaa0ff]">CASE FILE</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-white md:text-4xl">Evidence, not opinions.</h2></div><Badge className={`border px-3 py-1.5 ${highRisk ? "border-red-300/20 bg-red-400/10 text-red-200" : "border-emerald-300/20 bg-emerald-400/10 text-emerald-200"}`}>{highRisk ? "IMPERSONATION CONFIRMED" : "IDENTITY CONSISTENT"}</Badge></div><div className="grid gap-5 xl:grid-cols-[1.12fr_.88fr]"><Card className="glass border-white/10"><CardContent className="p-6 md:p-7"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-xs text-[#aea3ff]">{result.investigation.case_number}</p><h3 className="mt-2 text-xl font-medium text-white">{scenario.subject}</h3><p className="mt-1 text-sm text-slate-500">Identity Genome {result.investigation.genome_version} · {result.investigation.artifact_reference}</p></div><span className={`grid size-12 place-items-center rounded-2xl ${highRisk ? "bg-red-400/10 text-red-200" : "bg-emerald-400/10 text-emerald-200"}`}>{highRisk ? <AlertTriangle className="size-6" /> : <ShieldCheck className="size-6" />}</span></div><div className="mt-8 grid gap-5 sm:grid-cols-[.9fr_1.1fr]"><div className="grid aspect-square max-h-48 place-items-center rounded-full border-[10px] border-[#8874f2] border-r-[#4cc9f8] border-b-[#4fe0ab] bg-[#101431]"><div className="text-center"><p className="font-mono text-4xl font-semibold text-white">{match}%</p><p className="mt-1 text-xs text-slate-500">IDENTITY MATCH</p></div></div><div className="space-y-4">{Object.entries(result.risk.breakdown).filter(([key]) => key !== "weighted_score").map(([key, value]) => <div key={key}><div className="mb-1.5 flex justify-between text-xs"><span className="capitalize text-slate-400">{key}</span><span className="font-mono text-slate-200">{Math.round(value * 100)}%</span></div><Progress value={value * 100} className="h-1.5 bg-white/[.08] [&>div]:bg-gradient-to-r [&>div]:from-[#9078ff] [&>div]:to-[#52c9fa]" /></div>)}</div></div><div className="mt-8 rounded-xl border border-white/[.07] bg-[#080b22]/60 p-4"><p className="text-xs font-medium tracking-wider text-slate-500">VERDICT</p><p className={`mt-2 text-lg font-medium ${highRisk ? "text-red-200" : "text-emerald-200"}`}>{highRisk ? "Impersonation confirmed" : "Identity consistent"}</p><p className="mt-1 text-sm leading-6 text-slate-400">The deterministic Risk Engine used the weighted signal breakdown shown above. No language model decides the outcome.</p></div></CardContent></Card>
      <Card className="glass border-white/10"><CardContent className="p-6"><div className="flex items-center gap-2"><Fingerprint className="size-4 text-[#ad9fff]" /><h3 className="font-medium text-white">Evidence & agent findings</h3></div><div className="mt-5 space-y-3">{evidence.map((item) => <div className="rounded-xl border border-white/[.07] bg-white/[.025] p-3" key={item.code}><div className="flex items-center justify-between gap-4"><p className="text-sm text-slate-200">{item.code.replaceAll("_", " ")}</p><span className="font-mono text-xs text-[#afa5ff]">{Math.round(item.weight * 100)}%</span></div><p className="mt-1 text-xs text-slate-500">Source: {item.source_reference}</p></div>)}{result.agents.map((item) => <div className="flex items-center gap-3 rounded-xl border border-white/[.05] px-3 py-2.5" key={item.agent}><span className="grid size-6 place-items-center rounded-full bg-white/[.06]"><Check className="size-3 text-[#a99bff]" /></span><div className="min-w-0 flex-1"><p className="capitalize text-sm text-slate-300">{item.agent}</p><p className="truncate text-xs text-slate-600">{item.findings[0]?.code.replaceAll("_", " ") ?? "Structured output complete"}</p></div><span className="font-mono text-xs text-slate-400">{Math.round(item.confidence * 100)}%</span></div>)}</div></CardContent></Card></div><Card className="glass mt-5 border-white/10"><CardContent className="p-6"><div className="flex items-center gap-2"><Clock3 className="size-4 text-[#ad9fff]" /><h3 className="font-medium text-white">Case timeline</h3></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{result.investigation.timeline.map((event, index) => <div className="relative flex gap-3" key={`${event.state}-${index}`}><span className="grid size-6 shrink-0 place-items-center rounded-full bg-emerald-400/10"><Check className="size-3 text-emerald-300" /></span><div><p className="text-sm text-slate-300">{labels[event.state] ?? event.state}</p><p className="mt-1 font-mono text-[10px] text-slate-600">{new Date(event.occurred_at).toLocaleTimeString()}</p></div></div>)}</div></CardContent></Card></section>;
}
