import { Check, Circle, LoaderCircle, ShieldCheck } from "lucide-react";
import { motion } from "framer-motion";
import { Card, CardContent } from "@/components/ui/card";

type InvestigationConsoleProps = { activeStep: number; caseNumber?: string };

const steps = ["Sentinel opened the investigation", "Evidence collected and artifact classified", "Genesis reconstructed Identity Genome", "Cipher compared writing signature", "Chronos validated case timeline", "ForensIQ inspected forensic signals", "Risk Engine classified evidence", "Atlas generated certificate and report"];

export function InvestigationConsole({ activeStep, caseNumber }: InvestigationConsoleProps) {
  return <section className="mx-auto w-full max-w-4xl px-5 py-8 md:px-10"><Card className="glass overflow-hidden border-[#9885fb]/25"><CardContent className="p-6 md:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-xs tracking-[.16em] text-[#aaa0ff]">LIVE INVESTIGATION</p><h2 className="mt-2 text-2xl font-semibold text-white">{caseNumber ?? "CASE INITIALIZING"}</h2></div><div className="flex items-center gap-2 rounded-full border border-[#a791ff]/20 bg-[#8a70f4]/10 px-3 py-1.5 text-xs text-[#c6bcff]"><LoaderCircle className="size-3.5 animate-spin" /> Sentinel coordinating</div></div><div className="relative mt-8 space-y-0">{steps.map((step, index) => { const complete = index < activeStep; const current = index === activeStep; return <motion.div initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .04 }} className="relative flex gap-4 pb-5" key={step}><div className="relative z-10 grid size-7 shrink-0 place-items-center rounded-full border border-white/10 bg-[#101431]">{complete ? <Check className="size-4 text-emerald-300" /> : current ? <LoaderCircle className="size-3.5 animate-spin text-[#b5a7ff]" /> : <Circle className="size-2 text-slate-600" />}</div>{index < steps.length - 1 && <div className="absolute left-[13px] top-7 h-[calc(100%-8px)] w-px bg-white/[.08]" />}<div className="pt-0.5"><p className={`text-sm ${complete || current ? "text-slate-100" : "text-slate-600"}`}>{step}</p><p className="mt-1 font-mono text-[10px] text-slate-600">{complete ? "COMPLETE" : current ? "IN PROGRESS" : "QUEUED"}</p></div></motion.div>; })}</div><div className="mt-2 flex items-center gap-2 border-t border-white/[.08] pt-5 text-xs text-slate-500"><ShieldCheck className="size-4 text-[#a899ff]" />Evidence is correlated against a versioned Identity Genome.</div></CardContent></Card></section>;
}
