import Link from "next/link";
import { Activity, ArrowRight, BadgeCheck, BellRing, FileText, Fingerprint, KeyRound, LockKeyhole, Radar, ShieldAlert, ShieldCheck, UploadCloud, UserRound, type LucideIcon } from "lucide-react";
import { IdentityGenomeHologram } from "@/components/identity-genome-hologram";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { PlatformShell } from "@/components/platform-shell";

export const platformSections = ["dashboard", "genome", "investigations", "cases", "certificates", "reports", "profile", "settings"] as const;
export type PlatformSection = typeof platformSections[number];

const sectionCopy: Record<Exclude<PlatformSection, "dashboard" | "genome">, { eyebrow: string; title: string; body: string; icon: LucideIcon; action: string; actionHref: string }> = {
  investigations: { eyebrow: "INVESTIGATIONS", title: "Open a new evidence-backed investigation.", body: "Real user artifacts require an authenticated Identity Genome. Judge Demo remains available to explore the complete backend investigation flow.", icon: ShieldAlert, action: "Try Judge Demo", actionHref: "/demo" },
  cases: { eyebrow: "CASE FILES", title: "Your resolved cases will appear here.", body: "No authenticated case history is available in this deployment. Case files are never invented or pre-populated.", icon: FileText, action: "Explore a demo case", actionHref: "/demo" },
  certificates: { eyebrow: "CERTIFICATES", title: "Portable trust credentials, backed by evidence.", body: "No certificates have been issued for an authenticated Identity Genome yet. Run the Judge Demo to review the existing certificate experience.", icon: BadgeCheck, action: "View demo certificate", actionHref: "/demo" },
  reports: { eyebrow: "EVIDENCE REPORTS", title: "Evidence stays readable, shareable, and traceable.", body: "No evidence reports are available without persisted user investigations. The demo uses the real existing report contract.", icon: FileText, action: "View demo report", actionHref: "/demo" },
  profile: { eyebrow: "PROFILE", title: "Your profile stays under your control.", body: "Authentication is not configured in this deployment, so no profile data is collected or displayed.", icon: UserRound, action: "Open authentication", actionHref: "/auth/login" },
  settings: { eyebrow: "SETTINGS", title: "Trust is configurable by design.", body: "Privacy, consent, notification, and connection settings become available once authentication is connected. No settings are simulated here.", icon: KeyRound, action: "Open authentication", actionHref: "/auth/login" },
};

export function PlatformWorkspace({ section }: { section: PlatformSection }) {
  if (section === "dashboard") return <Dashboard />;
  if (section === "genome") return <GenomeWorkspace />;
  const content = sectionCopy[section];
  const Icon = content.icon;
  return <PlatformShell active={section}><section className="mx-auto flex min-h-[calc(100vh-73px)] max-w-5xl items-center px-5 py-12 md:px-8"><Card className="glass w-full border-white/[.1]"><CardContent className="max-w-2xl p-7 md:p-10"><span className="grid size-12 place-items-center rounded-2xl bg-[#8b78f6]/15 text-[#c0b6ff]"><Icon aria-hidden="true" className="size-6" /></span><p className="mt-8 font-mono text-[11px] tracking-[.16em] text-[#afa4ff]">{content.eyebrow}</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-white md:text-4xl">{content.title}</h1><p className="mt-5 text-sm leading-7 text-slate-400 md:text-base">{content.body}</p><div className="mt-8 rounded-xl border border-amber-200/10 bg-amber-300/[.05] px-4 py-3 text-xs leading-5 text-amber-100">Preview mode is active. This workspace does not fabricate account, monitoring, or investigation records.</div><Button asChild className="mt-7 h-11 rounded-xl bg-[#8b78f6] text-white hover:bg-[#9c8aff]"><Link href={content.actionHref}>{content.action}<ArrowRight className="size-4" /></Link></Button></CardContent></Card></section></PlatformShell>;
}

function Dashboard() {
  return <PlatformShell active="dashboard"><section className="mx-auto max-w-7xl px-5 py-8 md:px-8 md:py-10"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="font-mono text-[11px] tracking-[.17em] text-[#aea3ff]">IDENTITY GUARDIAN</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white md:text-4xl">Your trust layer is standing by.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Connect authentication and verified identity sources to create a persistent Identity Genome. This deployment shows the platform shell without inventing user data.</p></div><Button asChild className="h-11 rounded-xl bg-[#8b78f6] text-white hover:bg-[#9c8aff]"><Link href="/onboarding">Create Identity Genome <ArrowRight className="size-4" /></Link></Button></div>
    <div className="mt-8 grid gap-5 xl:grid-cols-[1.05fr_.95fr]"><Card className="glass overflow-hidden border-white/[.1]"><CardContent className="grid gap-5 p-5 sm:grid-cols-[.86fr_1.14fr] sm:p-6"><IdentityGenomeHologram phase="idle" identityLabel="Platform Preview" status="Not connected" currentState="Guardian waiting for verified sources" /><div className="flex flex-col justify-between"><div><p className="font-mono text-[10px] tracking-[.16em] text-slate-500">GUARDIAN STATUS</p><div className="mt-3 flex items-center gap-2 text-sm text-slate-200"><span className="size-2 rounded-full bg-amber-300 shadow-[0_0_12px_#fcd34d]" />Awaiting Identity Genome</div><p className="mt-4 text-sm leading-6 text-slate-400">The Guardian becomes a permanent companion after authenticated source ingestion. It does not claim to monitor data that has not been connected.</p></div><div className="mt-6 grid grid-cols-2 gap-3"><Metric label="Identity health" value="—" detail="No genome" /><Metric label="Trust rating" value="—" detail="No certificate" /><Metric label="Confidence" value="—" detail="No signals" /><Metric label="Genome version" value="—" detail="Not created" /></div></div></CardContent></Card>
      <Card className="glass border-white/[.1]"><CardContent className="p-6"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] tracking-[.16em] text-slate-500">CONTINUOUS PROTECTION</p><h2 className="mt-2 text-xl font-medium text-white">Guardian monitoring</h2></div><Radar aria-hidden="true" className="size-6 text-[#afa4ff]" /></div><div className="mt-6 rounded-2xl border border-amber-200/10 bg-amber-300/[.05] p-4"><p className="text-sm font-medium text-amber-100">Monitoring preview only</p><p className="mt-2 text-xs leading-5 text-slate-400">Live monitoring is not implemented by the frozen backend, so TrustDNA is not reporting a fabricated “all clear.”</p></div><ul className="mt-5 space-y-3 text-sm">{["Identity Genome", "Uploaded documents", "Writing samples", "Resume"].map((item) => <li className="flex items-center justify-between rounded-xl border border-white/[.06] bg-black/10 px-3 py-2.5" key={item}><span className="text-slate-300">{item}</span><span className="font-mono text-[10px] tracking-[.12em] text-slate-600">NOT CONNECTED</span></li>)}</ul><div className="mt-5 flex flex-wrap gap-2">{["Google", "GitHub", "LinkedIn", "Gmail"].map((item) => <span key={item} className="rounded-full border border-white/[.08] px-2.5 py-1 font-mono text-[9px] tracking-[.1em] text-slate-600">{item} · COMING SOON</span>)}</div></CardContent></Card></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-3"><DashboardPanel icon={Activity} eyebrow="IDENTITY TIMELINE" title="No verified activity yet" body="Start onboarding to connect consented identity sources." href="/onboarding" action="Create Genome" /><DashboardPanel icon={BellRing} eyebrow="THREAT FEED" title="No live feed available" body="Monitoring remains explicitly unavailable until a service is connected." href="/settings" action="View settings" /><DashboardPanel icon={FileText} eyebrow="RECENT RECORDS" title="No persisted investigations" body="Use Judge Demo to experience the existing real investigation flow." href="/demo" action="Try Demo" /></div>
    <div className="mt-5 grid gap-5 md:grid-cols-2"><Card className="glass border-white/[.1]"><CardContent className="p-6"><p className="font-mono text-[10px] tracking-[.16em] text-slate-500">QUICK ACTIONS</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><QuickAction icon={ShieldAlert} title="New Investigation" body="Requires an authenticated genome" href="/investigations" /><QuickAction icon={ShieldCheck} title="Try Demo" body="Run the real Judge Mode pipeline" href="/demo" /><QuickAction icon={Fingerprint} title="Identity Genome" body="Connect consented sources" href="/onboarding" /><QuickAction icon={FileText} title="Evidence Reports" body="Review existing demo output" href="/reports" /></div></CardContent></Card><Card className="glass border-white/[.1]"><CardContent className="p-6"><p className="font-mono text-[10px] tracking-[.16em] text-slate-500">RECENT CERTIFICATES</p><div className="mt-5 flex min-h-48 flex-col items-center justify-center rounded-2xl border border-dashed border-white/[.1] bg-black/10 text-center"><BadgeCheck aria-hidden="true" className="size-6 text-slate-600" /><p className="mt-3 text-sm font-medium text-slate-300">No certificates issued</p><p className="mt-1 max-w-xs text-xs leading-5 text-slate-500">Certificates are created from completed, persisted investigations—not demo placeholders.</p></div></CardContent></Card></div>
  </section></PlatformShell>;
}

function GenomeWorkspace() {
  return <PlatformShell active="genome"><section className="mx-auto max-w-6xl px-5 py-8 md:px-8 md:py-10"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="font-mono text-[11px] tracking-[.17em] text-[#aea3ff]">IDENTITY GENOME</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white md:text-4xl">Build the evidence model of you.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Writing traits, consented source coverage, and versioned evidence form an explainable Identity Genome.</p></div><Button asChild className="h-11 rounded-xl bg-[#8b78f6] text-white hover:bg-[#9c8aff]"><Link href="/onboarding">Start onboarding <ArrowRight className="size-4" /></Link></Button></div><div className="mt-8 grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><IdentityGenomeHologram phase="genome_creation" identityLabel="Genome not created" status="Awaiting sources" currentState="Connect consented sources to begin" /><Card className="glass border-white/[.1]"><CardContent className="p-6"><p className="font-mono text-[10px] tracking-[.16em] text-slate-500">SOURCE COVERAGE</p><h2 className="mt-2 text-xl font-medium text-white">Consent before collection.</h2><p className="mt-3 text-sm leading-6 text-slate-400">No sources have been uploaded or persisted in this preview. Connect only what you want your Identity Genome to learn from.</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{[{ icon: FileText, label: "Resume" }, { icon: Fingerprint, label: "Writing sample" }, { icon: UploadCloud, label: "Portfolio" }, { icon: Activity, label: "Voice sample" }].map(({ icon: Icon, label }) => <div className="rounded-xl border border-white/[.08] bg-black/10 p-4" key={label}><Icon aria-hidden="true" className="size-4 text-[#b4a9ff]" /><p className="mt-4 text-sm text-slate-200">{label}</p><p className="mt-1 font-mono text-[9px] tracking-[.12em] text-slate-600">NOT CONNECTED</p></div>)}</div><p className="mt-6 flex items-center gap-2 text-xs text-slate-500"><LockKeyhole aria-hidden="true" className="size-3.5" />Identity sources remain local to the preview until authentication and persistence are connected.</p></CardContent></Card></div></section></PlatformShell>;
}

function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-xl border border-white/[.07] bg-black/10 p-3"><p className="font-mono text-[9px] tracking-[.12em] text-slate-600">{label.toUpperCase()}</p><p className="mt-2 text-lg font-semibold text-white">{value}</p><p className="mt-1 text-[10px] text-slate-500">{detail}</p></div>; }
function DashboardPanel({ icon: Icon, eyebrow, title, body, href, action }: { icon: LucideIcon; eyebrow: string; title: string; body: string; href: string; action: string }) { return <Card className="glass border-white/[.1]"><CardContent className="p-5"><Icon aria-hidden="true" className="size-5 text-[#b6abff]" /><p className="mt-5 font-mono text-[9px] tracking-[.14em] text-slate-600">{eyebrow}</p><h2 className="mt-2 text-base font-medium text-white">{title}</h2><p className="mt-2 text-xs leading-5 text-slate-400">{body}</p><Link href={href} className="mt-5 inline-flex items-center gap-1.5 text-xs text-[#b9afff] hover:text-white">{action}<ArrowRight className="size-3.5" /></Link></CardContent></Card>; }
function QuickAction({ icon: Icon, title, body, href }: { icon: LucideIcon; title: string; body: string; href: string }) { return <Link href={href} className="rounded-xl border border-white/[.08] bg-black/10 p-4 transition hover:border-[#b1a5ff]/35 hover:bg-white/[.04]"><Icon aria-hidden="true" className="size-4 text-[#b8adff]" /><p className="mt-4 text-sm font-medium text-white">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{body}</p></Link>; }
