"use client";

import { useRef, useState } from "react";
import { motion } from "framer-motion";
import { Activity, Bell, Check, ChevronRight, Clock3, FileUp, Grid2X2, HelpCircle, History, LoaderCircle, Menu, MoreHorizontal, Plus, ScanFace, Settings, ShieldAlert, ShieldCheck, Sparkles, X } from "lucide-react";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Separator } from "@/components/ui/separator";
import { BrandMark } from "@/components/brand-mark";
import { identitySignals, recentVerifications } from "@/lib/mock-data";

const navItems = [{ icon: Grid2X2, label: "Overview" }, { icon: ScanFace, label: "Verify identity" }, { icon: History, label: "Verification history" }, { icon: Activity, label: "Threat intelligence" }];

export function TrustDashboard() {
  const [fileName, setFileName] = useState<string | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [showResult, setShowResult] = useState(false);
  const picker = useRef<HTMLInputElement>(null);

  function selectFile(file?: File) { if (file) { setFileName(file.name); setShowResult(false); } }
  function analyze() { if (!fileName) return picker.current?.click(); setIsAnalyzing(true); setTimeout(() => { setIsAnalyzing(false); setShowResult(true); }, 1150); }

  return <main className="app-backdrop min-h-screen overflow-hidden">
    <div className="grid-overlay fixed inset-0 pointer-events-none opacity-50" />
    <div className="relative mx-auto flex min-h-screen max-w-[1540px]">
      <aside className="hidden w-[258px] shrink-0 flex-col border-r border-white/[.08] bg-[#090c24]/75 px-5 py-7 backdrop-blur-xl lg:flex">
        <BrandMark />
        <nav className="mt-12 space-y-1">{navItems.map((item, index) => <button key={item.label} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm transition ${index === 0 ? "bg-[#7865ed]/18 text-white" : "text-slate-400 hover:bg-white/5 hover:text-white"}`}><item.icon className="size-[18px]" />{item.label}{index === 0 && <span className="ml-auto size-1.5 rounded-full bg-[#8f7cff] shadow-[0_0_10px_#a390ff]" />}</button>)}</nav>
        <div className="mt-auto space-y-5"><Card className="glass border-white/10"><CardContent className="p-4"><div className="flex items-center gap-2 text-xs text-[#b9aeff]"><Sparkles className="size-3.5" /> DIGITAL TWIN</div><p className="mt-2 text-sm font-medium">Ready to protect you</p><p className="mt-1 text-xs leading-5 text-slate-400">Your twin learns securely from 5 trusted sources.</p><Button variant="ghost" className="mt-2 h-auto w-full justify-between px-0 py-1 text-xs text-[#a99cff] hover:bg-transparent hover:text-white">Manage sources <ChevronRight className="size-3.5" /></Button></CardContent></Card><button className="flex items-center gap-3 px-3 text-sm text-slate-400 hover:text-white"><Settings className="size-[18px]" /> Settings</button><button className="flex items-center gap-3 px-3 text-sm text-slate-400 hover:text-white"><HelpCircle className="size-[18px]" /> Support</button></div>
      </aside>
      <section className="flex min-w-0 flex-1 flex-col px-5 pb-10 pt-5 md:px-8 lg:px-10">
        <header className="flex items-center justify-between"><div className="flex items-center gap-3 lg:hidden"><Menu className="size-5 text-slate-300" /><BrandMark compact /></div><div className="hidden lg:block"><p className="text-xs text-slate-400">Thursday, July 17</p><p className="mt-1 text-sm font-medium text-slate-200">Your identity is protected</p></div><div className="flex items-center gap-3"><button className="relative grid size-9 place-items-center rounded-full border border-white/10 bg-white/5 text-slate-300"><Bell className="size-4" /><span className="absolute right-1 top-1 size-1.5 rounded-full bg-[#a48dff]" /></button><Avatar className="size-9 border border-white/15"><AvatarFallback className="bg-gradient-to-br from-[#5a50a9] to-[#2a87bd] text-xs font-semibold">AS</AvatarFallback></Avatar></div></header>
        <div className="mt-10 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-[#9b8eff]">IDENTITY COMMAND CENTER</p><h1 className="mt-2 text-3xl font-semibold tracking-tight md:text-4xl">Good morning, Aisha.</h1><p className="mt-3 text-sm text-slate-400">Everything that matters to your digital identity, in one place.</p></div><Button onClick={() => picker.current?.click()} className="h-11 gap-2 rounded-xl bg-[#8b78f6] px-5 text-white shadow-lg shadow-violet-950/70 hover:bg-[#9a89ff]"><Plus className="size-4" />New verification</Button></div>
        <input ref={picker} className="hidden" type="file" accept=".pdf,.doc,.docx,.txt,.wav,.mp3,.png,.jpg,.jpeg" onChange={(e) => selectFile(e.target.files?.[0])} />
        <section className="mt-8 grid gap-5 xl:grid-cols-[1.22fr_.78fr]">
          <Card className="glass overflow-hidden border-white/10"><CardContent className="p-6 md:p-7"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-400">Identity health</p><div className="mt-2 flex items-end gap-3"><span className="text-5xl font-semibold tracking-tighter">94</span><span className="mb-2 text-base text-slate-500">/100</span></div><div className="mt-3 flex items-center gap-2 text-sm text-emerald-300"><span className="grid size-5 place-items-center rounded-full bg-emerald-400/15"><Check className="size-3" /></span>Strong &amp; secure</div></div><div className="grid size-24 place-items-center rounded-full border-[7px] border-[#8b7cff] border-r-[#51c8fb] border-b-[#3de3a7] bg-[#111634] shadow-[0_0_30px_rgb(118_102_243/.25)]"><ShieldCheck className="size-9 text-[#d9d4ff]" /></div></div><Separator className="my-6 bg-white/10" /><div className="grid grid-cols-2 gap-y-5 md:grid-cols-4">{[{v:"5",l:"Trusted sources"},{v:"24",l:"Verifications"},{v:"1",l:"Active threat",warn:true},{v:"100%",l:"Twin coverage"}].map(s => <div key={s.l}><p className={`font-mono text-xl font-semibold ${s.warn ? "text-amber-300" : "text-white"}`}>{s.v}</p><p className="mt-1 text-xs text-slate-500">{s.l}</p></div>)}</div></CardContent></Card>
          <Card className="glass border-white/10"><CardContent className="p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-medium">Potential impersonation</p><p className="mt-1 text-xs text-slate-400">Unusual email identity detected</p></div><span className="grid size-10 place-items-center rounded-full bg-amber-400/10 text-amber-300"><ShieldAlert className="size-5" /></span></div><div className="mt-5 flex items-center justify-between rounded-xl border border-amber-300/10 bg-amber-300/[.06] px-3 py-2.5"><div className="flex items-center gap-2 text-xs text-slate-300"><span className="size-2 rounded-full bg-amber-300" />Medium risk</div><span className="font-mono text-xs text-amber-200">58% match</span></div><Button variant="ghost" className="mt-3 h-8 w-full justify-between text-xs text-[#b0a4ff] hover:bg-white/5 hover:text-white">Review threat <ChevronRight className="size-3.5" /></Button></CardContent></Card>
        </section>
        <section className="mt-5 grid gap-5 xl:grid-cols-[1.22fr_.78fr]">
          <Card className="glass border-white/10"><CardContent className="p-6"><div className="flex items-center justify-between"><div><h2 className="font-medium">Verify a digital artifact</h2><p className="mt-1 text-xs text-slate-400">Compare any file to your living identity signature.</p></div><span className="rounded-lg bg-[#7661ec]/15 p-2 text-[#ab9dff]"><ScanFace className="size-5" /></span></div><button onClick={() => picker.current?.click()} className="mt-5 flex min-h-28 w-full flex-col items-center justify-center rounded-xl border border-dashed border-[#8f81ed]/45 bg-[#7561dd]/[.07] p-4 text-center transition hover:bg-[#7561dd]/[.13]"><FileUp className="size-6 text-[#a899ff]" />{fileName ? <><p className="mt-2 text-sm font-medium text-white">{fileName}</p><p className="mt-1 text-xs text-slate-400">Ready for analysis</p></> : <><p className="mt-2 text-sm font-medium text-slate-200">Drop a file here or <span className="text-[#a99aff]">browse</span></p><p className="mt-1 text-xs text-slate-500">Email, document, voice, image or certificate</p></>}</button><div className="mt-4 flex items-center justify-between gap-3"><p className="text-xs text-slate-500">Files are encrypted and never used to train models.</p><Button onClick={analyze} disabled={isAnalyzing} className="h-9 gap-2 rounded-lg bg-[#8b78f6] px-4 text-xs text-white hover:bg-[#9a89ff]">{isAnalyzing ? <LoaderCircle className="size-3.5 animate-spin" /> : <Sparkles className="size-3.5" />}{isAnalyzing ? "Analyzing" : "Verify now"}</Button></div>{showResult && <motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="mt-4 flex items-center gap-3 rounded-xl border border-emerald-400/15 bg-emerald-400/[.07] p-3"><div className="grid size-9 place-items-center rounded-full bg-emerald-400/15 text-emerald-300"><ShieldCheck className="size-5" /></div><div className="min-w-0"><p className="text-sm font-medium text-emerald-100">Authentic identity match · 96%</p><p className="mt-0.5 truncate text-xs text-emerald-100/60">Writing signature, semantic fingerprint and timeline are consistent.</p></div><button onClick={() => setShowResult(false)} className="ml-auto text-emerald-200/60"><X className="size-4" /></button></motion.div>}</CardContent></Card>
          <Card className="glass border-white/10"><CardContent className="p-6"><div className="flex items-center justify-between"><div><h2 className="font-medium">Digital twin status</h2><p className="mt-1 text-xs text-slate-400">Last learned 18 minutes ago</p></div><Badge className="border-0 bg-emerald-400/12 text-emerald-300 hover:bg-emerald-400/12">Active</Badge></div><div className="mt-5 space-y-4">{identitySignals.map(signal => <div key={signal.label}><div className="mb-1.5 flex justify-between text-xs"><span className="text-slate-400">{signal.label}</span><span className="font-mono text-slate-200">{signal.value}%</span></div><Progress value={signal.value} className="h-1.5 bg-white/8 [&>div]:bg-gradient-to-r [&>div]:from-[#8d78ff] [&>div]:to-[#54c5fa]" /></div>)}</div><Button variant="ghost" className="mt-4 h-8 w-full justify-between border-t border-white/[.08] pt-5 text-xs text-[#b0a4ff] hover:bg-transparent hover:text-white">View twin profile <ChevronRight className="size-3.5" /></Button></CardContent></Card>
        </section>
        <section className="mt-5"><Card className="glass border-white/10"><CardContent className="p-0"><div className="flex items-center justify-between px-6 py-5"><div><h2 className="font-medium">Recent verifications</h2><p className="mt-1 text-xs text-slate-400">Your identity trust trail</p></div><Button variant="ghost" className="h-8 gap-1 text-xs text-[#ada1ff] hover:bg-white/5 hover:text-white">View all <ChevronRight className="size-3.5" /></Button></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-y border-white/[.07] text-[11px] uppercase tracking-wider text-slate-500"><tr><th className="px-6 py-3 font-medium">Artifact</th><th className="py-3 font-medium">Authenticity</th><th className="py-3 font-medium">Status</th><th className="py-3 font-medium">Verified</th><th className="px-6 py-3" /></tr></thead><tbody>{recentVerifications.map(item => <tr className="border-b border-white/[.055] last:border-0" key={item.name}><td className="px-6 py-4"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-white/[.06] text-slate-300"><item.icon className="size-4" /></span><div><p className="font-medium text-slate-200">{item.name}</p><p className="text-xs text-slate-500">{item.type}</p></div></div></td><td className="py-4"><span className={`font-mono text-xs ${item.score > 80 ? "text-emerald-300" : "text-amber-300"}`}>{item.score}%</span></td><td className="py-4"><Badge className={`border-0 text-[10px] ${item.state === "Verified" ? "bg-emerald-400/10 text-emerald-300 hover:bg-emerald-400/10" : "bg-amber-400/10 text-amber-300 hover:bg-amber-400/10"}`}>{item.state}</Badge></td><td className="py-4 text-xs text-slate-500"><span className="inline-flex items-center gap-1"><Clock3 className="size-3" />{item.time}</span></td><td className="px-6 py-4 text-right"><MoreHorizontal className="ml-auto size-4 text-slate-500" /></td></tr>)}</tbody></table></div></CardContent></Card></section>
      </section>
    </div>
  </main>;
}
