import { CheckCircle2, QrCode, ShieldCheck } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import type { InvestigationResult } from "@/features/judge/types";

export function TrustCertificate({ result }: { result: InvestigationResult }) {
  const certificate = result.certificate;
  return <section className="mx-auto w-full max-w-7xl px-5 py-8 md:px-10"><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-medium tracking-[.18em] text-[#aaa0ff]">TRUSTDNA CERTIFICATE</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-white">A portable trust credential.</h2><p className="mt-3 max-w-md text-sm leading-6 text-slate-400">The certificate is structured evidence first—ready for a public verification route, QR code, HTML, and export rendering without changing the investigation contract.</p></div><Card className="glass overflow-hidden border-[#a791ff]/30"><CardContent className="relative p-6 md:p-7"><div className="absolute -right-12 -top-12 size-44 rounded-full bg-[#705ee7]/25 blur-3xl" /><div className="relative flex items-start justify-between"><div><p className="font-mono text-xs tracking-[.15em] text-[#b4a8ff]">TRUSTDNA AI</p><p className="mt-2 text-xl font-medium text-white">Identity Trust Certificate</p></div><ShieldCheck className="size-8 text-[#b4a8ff]" /></div><div className="relative mt-8 grid gap-5 sm:grid-cols-3"><Metric label="TRUST RATING" value={certificate.trust_rating} /><Metric label="CONFIDENCE" value={`${Math.round(certificate.identity_confidence * 100)}%`} /><Metric label="GENOME" value={result.investigation.genome_version.toUpperCase()} /></div><div className="relative mt-7 grid gap-5 border-t border-white/[.1] pt-5 sm:grid-cols-[1fr_auto]"><div className="space-y-2 text-sm"><p className="text-slate-400">Certificate ID <span className="ml-2 font-mono text-slate-200">{certificate.certificate_number}</span></p><p className="text-slate-400">Case reference <span className="ml-2 font-mono text-slate-200">{result.investigation.case_number}</span></p><p className="text-slate-400">Issued <span className="ml-2 font-mono text-slate-200">{new Date(certificate.issued_at).toLocaleString()}</span></p></div><div className="grid size-20 place-items-center rounded-xl border border-white/10 bg-white/[.04]"><QrCode className="size-10 text-slate-300" /></div></div><div className="relative mt-5 flex items-center gap-2 text-xs text-emerald-200"><CheckCircle2 className="size-4" /> Certificate generated from structured case evidence.</div></CardContent></Card></div></section>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] tracking-[.12em] text-slate-500">{label}</p><p className="mt-1 font-mono text-xl font-semibold text-white">{value}</p></div>; }
