import { Fingerprint, Network, ShieldCheck } from "lucide-react";
import { Progress } from "@/components/ui/progress";
import { ProvenanceBadge } from "@/features/identity-intelligence/components/provenance-badge";
import type { GenomeSnapshot } from "@/features/identity-intelligence/types";

export function IdentityMap({ snapshot }: { snapshot: GenomeSnapshot }) {
  const nodes = snapshot.knowledgeGraph.nodes.slice(0, 6);
  const confidence = snapshot.genomeConfidence;
  return <section aria-labelledby="identity-map-heading" className="glass relative overflow-hidden rounded-2xl border border-white/[.1] p-5"><div aria-hidden="true" className="absolute -right-16 -top-16 size-48 rounded-full bg-cyan-400/[.06] blur-3xl" /><div className="relative flex items-start justify-between gap-4"><div><p className="font-mono text-[10px] tracking-[.16em] text-[#b6acff]">LIVE IDENTITY MAP</p><h2 id="identity-map-heading" className="mt-2 text-xl font-medium text-white">Explainable Genome Topology</h2><p className="mt-2 max-w-xl text-xs leading-5 text-slate-400">The map connects only consented source evidence with extracted and derived knowledge objects.</p></div><ProvenanceBadge origin={snapshot.hasExtractedKnowledge ? "derived" : "awaiting_evidence"} /></div>
    <div className="relative mt-6 grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><div className="relative min-h-52 overflow-hidden rounded-2xl border border-white/[.07] bg-[#050a20]/80" role="img" aria-label={snapshot.hasExtractedKnowledge ? "Identity map connecting the Identity Genome to analyzed text sources and extracted communication knowledge." : "Identity map awaiting the first supported source."}><div aria-hidden="true" className="absolute inset-0 bg-[radial-gradient(circle_at_50%_50%,rgb(123_104_244_/_16%),transparent_54%)]" /><svg aria-hidden="true" viewBox="0 0 420 220" className="absolute inset-0 size-full"><path d="M210 110L84 50M210 110L335 55M210 110L78 172M210 110L342 168" stroke="rgb(156 141 255 / 36%)" strokeWidth="1.2" strokeDasharray="4 7" /><circle cx="210" cy="110" r="44" fill="rgb(139 124 255 / 16%)" stroke="rgb(182 172 255 / 75%)" /><circle cx="210" cy="110" r="28" fill="rgb(77 214 255 / 10%)" stroke="rgb(125 232 255 / 60%)" />{[[84, 50], [335, 55], [78, 172], [342, 168]].map(([cx, cy], index) => <g key={`${cx}-${cy}`}><circle cx={cx} cy={cy} r="19" fill={snapshot.hasExtractedKnowledge ? "rgb(82 207 245 / 12%)" : "rgb(148 163 184 / 8%)"} stroke={snapshot.hasExtractedKnowledge ? "rgb(126 231 255 / 55%)" : "rgb(148 163 184 / 32%)"} /><text x={cx} y={cy + 3} textAnchor="middle" fill={snapshot.hasExtractedKnowledge ? "#c9f8ff" : "#94a3b8"} fontSize="9" fontFamily="monospace">0{index + 1}</text></g>)}</svg><div className="absolute inset-0 grid place-items-center"><div className="grid size-14 place-items-center rounded-full border border-cyan-200/30 bg-cyan-300/[.07] text-cyan-100 shadow-[0_0_38px_rgb(56_189_248_/_18%)]"><Fingerprint aria-hidden="true" className="size-5" /></div></div><div className="absolute inset-x-4 bottom-3 flex items-center justify-between font-mono text-[8px] tracking-[.13em] text-slate-500"><span>IDENTITY.GENOME</span><span>{snapshot.hasExtractedKnowledge ? "EVIDENCE LINKED" : "AWAITING SOURCE"}</span></div></div>
      <div className="grid content-start gap-3"><div className="grid gap-3 sm:grid-cols-2"><Metric label="Genome version" value={snapshot.latestVersion?.version ?? "Pending"} detail={snapshot.fingerprint ? `FP ${snapshot.fingerprint.slice(0, 10)}…` : "No fingerprint yet"} /><Metric label="Identity confidence" value={confidence === undefined ? "Pending" : `${confidence}%`} detail={confidence === undefined ? "Awaiting evidence" : "Genome-level confidence"} /><Metric label="Evidence sources" value={snapshot.sourceCount.toString()} detail={snapshot.sourceCount ? "Text sources analyzed" : "None yet"} /><Metric label="Knowledge objects" value={snapshot.knowledgeObjects.length.toString()} detail={snapshot.knowledgeObjects.length ? "Explainable facts" : "No facts inferred"} /></div>{confidence !== undefined && <div className="rounded-xl border border-white/[.07] bg-black/10 p-4"><div className="flex items-center justify-between gap-3"><p className="font-mono text-[9px] tracking-[.13em] text-slate-500">CONFIDENCE BREAKDOWN</p><span className="font-mono text-xs text-cyan-100">{confidence}%</span></div><Progress value={confidence} className="mt-3 bg-white/[.08] [&>[data-slot=progress-indicator]]:bg-gradient-to-r [&>[data-slot=progress-indicator]]:from-[#8d79f7] [&>[data-slot=progress-indicator]]:to-cyan-300" /><p className="mt-2 text-[11px] leading-5 text-slate-500">This is the backend&apos;s version-level confidence—not an inferred personality score.</p></div>}<div className="rounded-xl border border-white/[.07] bg-black/10 p-4"><div className="flex items-center gap-2"><Network aria-hidden="true" className="size-3.5 text-[#b7adff]" /><p className="font-mono text-[9px] tracking-[.13em] text-slate-500">MAP NODES</p></div><p className="mt-2 text-xs leading-5 text-slate-400">{nodes.map((node) => node.label).join(" · ") || "Identity Genome"}</p></div></div>
    </div>
  </section>;
}

function Metric({ label, value, detail }: { label: string; value: string; detail: string }) {
  return <div className="rounded-xl border border-white/[.07] bg-black/10 p-3"><div className="flex items-center gap-2"><ShieldCheck aria-hidden="true" className="size-3 text-[#b7adff]" /><p className="font-mono text-[8px] tracking-[.12em] text-slate-600">{label.toUpperCase()}</p></div><p className="mt-2 text-lg font-semibold text-white">{value}</p><p className="mt-1 text-[10px] text-slate-500">{detail}</p></div>;
}
