import { CheckCircle2, FileText, LockKeyhole, Sparkles } from "lucide-react";
import { primarySources } from "@/features/identity-intelligence/source-registry";
import type { SourceRecord } from "@/features/identity-intelligence/types";

export function SourceCoverage({ sources }: { sources: SourceRecord[] }) {
  return <section aria-labelledby="source-coverage-heading" className="glass rounded-2xl border border-white/[.09] p-5"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-[10px] tracking-[.16em] text-[#b6acff]">SOURCE COVERAGE</p><h2 id="source-coverage-heading" className="mt-2 text-xl font-medium text-white">Build with consented evidence</h2><p className="mt-2 text-xs leading-5 text-slate-400">Only analyzed sources become evidence. Unsupported sources remain unavailable until their extractor is ready.</p></div><LockKeyhole aria-hidden="true" className="size-5 text-[#b6acff]" /></div>
    <ul className="mt-6 grid gap-3 sm:grid-cols-2">{primarySources.map((source) => { const records = sources.filter((record) => record.sourceId === source.id); const ingested = records.length > 0; return <li key={source.id} className="rounded-xl border border-white/[.07] bg-black/10 p-4"><div className="flex items-start justify-between gap-3"><span className={`grid size-8 place-items-center rounded-lg ${ingested ? "bg-cyan-300/[.1] text-cyan-100" : source.availability === "text_ready" ? "bg-[#8e7af6]/10 text-[#c4bcff]" : "bg-white/[.04] text-slate-600"}`}>{ingested ? <CheckCircle2 aria-hidden="true" className="size-4" /> : source.availability === "text_ready" ? <FileText aria-hidden="true" className="size-4" /> : <Sparkles aria-hidden="true" className="size-4" />}</span><span className={`rounded-full border px-2 py-1 font-mono text-[8px] tracking-[.11em] ${ingested ? "border-cyan-300/20 bg-cyan-300/[.08] text-cyan-100" : source.availability === "text_ready" ? "border-violet-300/20 bg-violet-300/[.07] text-violet-100" : "border-white/[.08] text-slate-600"}`}>{ingested ? `${records.length} ANALYZED` : source.availability === "text_ready" ? "TEXT READY" : "COMING SOON"}</span></div><p className="mt-4 text-sm font-medium text-slate-200">{source.label}</p><p className="mt-1 text-[11px] leading-5 text-slate-500">{ingested ? records.map((record) => record.label).join(", ") : source.description}</p></li>; })}</ul>
  </section>;
}
