"use client";

import { useEffect, useMemo, useState } from "react";
import { motion, useReducedMotion } from "framer-motion";
import { Activity, BrainCircuit, CircleAlert, FileDown, FileJson, FileText, Lightbulb, RefreshCw, ShieldCheck, Sparkles, TrendingUp } from "lucide-react";
import { useAuth } from "@/components/auth-provider";
import { Button } from "@/components/ui/button";
import { buildGenomeSnapshot, emptyGenomeSnapshot } from "@/features/identity-intelligence/adapter";
import { IntelligenceApiError, loadGenomeIntelligence } from "@/features/identity-intelligence/api";
import { browserGenomeStore } from "@/features/identity-intelligence/session";
import type { GenomeSnapshot } from "@/features/identity-intelligence/types";
import { knowledgeRepository } from "@/features/identity-knowledge/knowledge-repository";
import { investigationHistory } from "@/features/investigation/investigation-history";
import { analyzeIdentity, type AnalystFinding } from "@/features/analyst/analyst-service";

export function AnalystWorkspace() {
  const { user } = useAuth();
  const userId = user?.uid;
  const reduceMotion = useReducedMotion();
  const [snapshot, setSnapshot] = useState<GenomeSnapshot>(() => emptyGenomeSnapshot());
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [attempt, setAttempt] = useState(0);
  useEffect(() => { let active = true; void (async () => { if (!userId) { if (active) setLoading(false); return; } const session = browserGenomeStore.load(userId); if (!session) { if (active) { setLoading(false); setError(null); } return; } try { const payload = await loadGenomeIntelligence(session.genomeId); const next = await buildGenomeSnapshot(payload, session.sources, knowledgeRepository.load(userId)); if (active) { setSnapshot(next); setError(null); } } catch (cause) { if (cause instanceof IntelligenceApiError && cause.status === 404) browserGenomeStore.clear(userId); if (active) setError("The Analyst could not load your current Identity Genome. Please retry or add a source."); } finally { if (active) setLoading(false); } })(); return () => { active = false; }; }, [attempt, userId]);
  const report = useMemo(() => analyzeIdentity(snapshot, userId ? investigationHistory.load(userId) : []), [snapshot, userId]);
  if (loading) return <Skeleton />;
  function download(kind: "json" | "markdown") { const content = kind === "json" ? JSON.stringify(report, null, 2) : toMarkdown(report); const blob = new Blob([content], { type: kind === "json" ? "application/json" : "text/markdown" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `trustdna-analyst-${new Date().toISOString().slice(0, 10)}.${kind === "json" ? "json" : "md"}`; anchor.click(); URL.revokeObjectURL(url); }
  return <section className="mx-auto max-w-[96rem] px-5 py-8 md:px-8 md:py-10"><motion.header initial={reduceMotion ? false : { opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: reduceMotion ? 0 : .32 }} className="flex flex-wrap items-end justify-between gap-5"><div><p className="font-mono text-[11px] tracking-[.17em] text-[#aea3ff]">TRUSTDNA AI ANALYST</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white md:text-4xl">Proactive insight, bounded by evidence.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">The Analyst inspects your current Identity Genome and metadata-only investigation history. It never invents a strength, weakness, or trend.</p></div><div className="flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={() => download("markdown")} className="border-white/[.12] bg-transparent text-slate-200 hover:bg-white/[.06] hover:text-white"><FileText className="size-3.5" />Markdown</Button><Button type="button" variant="outline" onClick={() => download("json")} className="border-white/[.12] bg-transparent text-slate-200 hover:bg-white/[.06] hover:text-white"><FileJson className="size-3.5" />JSON</Button><Button type="button" variant="outline" onClick={() => window.print()} className="border-white/[.12] bg-transparent text-slate-200 hover:bg-white/[.06] hover:text-white"><FileDown className="size-3.5" />Save as PDF</Button></div></motion.header>{error && <div role="status" className="mt-6 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-amber-200/15 bg-amber-200/[.06] p-4"><div className="flex gap-3"><CircleAlert className="mt-0.5 size-4 text-amber-200" /><p className="text-xs leading-5 text-amber-50">{error}</p></div><Button type="button" onClick={() => { setLoading(true); setAttempt((value) => value + 1); }} variant="outline" className="border-amber-200/20 bg-transparent text-amber-50"><RefreshCw className="size-3.5" />Retry</Button></div>}
    <section className="mt-7 overflow-hidden rounded-[1.7rem] border border-cyan-300/[.14] bg-gradient-to-br from-cyan-300/[.1] via-[#8d79f7]/[.08] to-black/[.15] p-5 sm:p-7"><div className="flex items-start gap-3"><BrainCircuit className="mt-0.5 size-5 text-cyan-200" /><div><p className="font-mono text-[10px] tracking-[.14em] text-cyan-100">EXECUTIVE SUMMARY</p><p className="mt-3 max-w-4xl text-lg leading-8 text-white">{report.executiveSummary}</p><p className="mt-4 font-mono text-[9px] tracking-[.1em] text-slate-500">ANALYZED {snapshot.knowledgeHistory.length} VERSIONED KNOWLEDGE OBJECTS · {report.investigations.total} RECORDED CASES</p></div></div></section>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><FindingSection icon={Sparkles} eyebrow="RECURRING STRENGTHS" title="Evidence-backed strengths" empty="No recurring strength is claimed until at least two relevant direct evidence objects are present." items={report.strengths} /><FindingSection icon={Lightbulb} eyebrow="GROWTH AREAS" title="Evidence gaps, not weaknesses" empty="No current evidence gap is detected in this view." items={report.growthAreas} /></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><FindingSection icon={TrendingUp} eyebrow="IDENTITY TRENDS" title="Versioned Genome evolution" empty="No trend can be shown until the first versioned source is available." items={report.trends} /><FindingSection icon={Activity} eyebrow="COMMUNICATION TRENDS" title="Measured communication signals" empty="Connect a consented text source to enable communication measurements." items={report.communication} /></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><FindingSection icon={ShieldCheck} eyebrow="EVIDENCE QUALITY" title="Confidence and provenance" empty="No quality metrics are available yet." items={report.quality} /><FindingSection icon={CircleAlert} eyebrow="KNOWLEDGE GAPS" title="What the Analyst cannot know yet" empty="No known gaps are currently returned." items={report.gaps} /></div>
    <section className="mt-5 glass rounded-[1.7rem] border border-white/[.1] p-5 sm:p-6"><p className="font-mono text-[10px] tracking-[.14em] text-[#c7beff]">RECOMMENDATIONS</p><h2 className="mt-2 text-xl font-medium text-white">Separate evidence, general advice, and unknowns.</h2><div className="mt-5 grid gap-4 lg:grid-cols-2">{report.recommendations.map((item) => <article key={item.id} className="rounded-2xl border border-white/[.08] bg-black/[.12] p-4"><h3 className="text-sm font-medium text-white">{item.title}</h3><RecommendationBlock title="Identity Evidence" values={item.identityEvidence} tone="cyan" /><RecommendationBlock title="General Advice" values={[item.generalAdvice]} tone="violet" /><RecommendationBlock title="Unknowns" values={item.unknowns} tone="amber" /></article>)}</div></section>
    <section className="mt-5 glass rounded-[1.7rem] border border-white/[.1] p-5 sm:p-6"><p className="font-mono text-[10px] tracking-[.14em] text-[#c7beff]">INSIGHT TIMELINE</p><h2 className="mt-2 text-xl font-medium text-white">Chronological, source-linked discoveries.</h2>{report.timeline.length ? <ol className="mt-5 space-y-3">{report.timeline.map((item) => <li key={item.id} className="flex gap-3 rounded-xl border border-white/[.07] bg-black/[.1] p-3"><span className="mt-1.5 size-2 shrink-0 rounded-full bg-cyan-200" /><div><p className="text-xs text-slate-200">{item.title}</p><p className="mt-1 text-[11px] leading-5 text-slate-500">{item.detail}</p><p className="mt-1 font-mono text-[8px] tracking-[.1em] text-slate-600">{formatDate(item.timestamp)}</p></div></li>)}</ol> : <p className="mt-5 rounded-xl border border-dashed border-white/[.1] p-5 text-xs text-slate-500">Timeline entries appear after the first analyzed, versioned source.</p>}</section>
  </section>;
}
function FindingSection({ icon: Icon, eyebrow, title, empty, items }: { icon: typeof Sparkles; eyebrow: string; title: string; empty: string; items: AnalystFinding[] }) { return <section className="glass rounded-[1.7rem] border border-white/[.1] p-5 sm:p-6"><div className="flex items-start gap-3"><Icon className="mt-0.5 size-4 text-[#c7beff]" /><div><p className="font-mono text-[10px] tracking-[.14em] text-[#c7beff]">{eyebrow}</p><h2 className="mt-1 text-lg font-medium text-white">{title}</h2></div></div>{items.length ? <div className="mt-5 space-y-3">{items.map((item) => <article key={item.id} className="rounded-xl border border-white/[.07] bg-black/[.12] p-4"><div className="flex flex-wrap items-start justify-between gap-2"><h3 className="text-sm text-slate-100">{item.title}</h3><span className="font-mono text-[9px] text-cyan-100">{item.confidence === null ? "EVIDENCE GAP" : `${Math.round(item.confidence * 100)}%`}</span></div><p className="mt-2 text-xs leading-5 text-slate-400">{item.detail}</p>{item.evidence.length > 0 && <p className="mt-3 border-t border-white/[.07] pt-3 text-[10px] leading-4 text-slate-500">{item.evidence.join(" · ")}</p>}</article>)}</div> : <p className="mt-5 rounded-xl border border-dashed border-white/[.1] p-5 text-xs leading-5 text-slate-500">{empty}</p>}</section>; }
function RecommendationBlock({ title, values, tone }: { title: string; values: string[]; tone: "cyan" | "violet" | "amber" }) { const color = tone === "cyan" ? "text-cyan-100" : tone === "violet" ? "text-[#cec7ff]" : "text-amber-100"; return <div className="mt-4"><p className={`font-mono text-[8px] tracking-[.12em] ${color}`}>{title.toUpperCase()}</p><p className="mt-1 text-[11px] leading-5 text-slate-500">{values.length ? values.join(" · ") : "No direct evidence selected."}</p></div>; }
function Skeleton() { return <section aria-label="Loading AI Analyst" className="mx-auto max-w-[96rem] animate-pulse px-5 py-8 md:px-8 md:py-10"><div className="h-3 w-48 rounded bg-white/[.08]" /><div className="mt-4 h-10 max-w-2xl rounded bg-white/[.08]" /><div className="mt-7 h-48 rounded-[1.7rem] bg-white/[.04]" /><div className="mt-5 grid gap-5 xl:grid-cols-2"><div className="h-80 rounded-[1.7rem] bg-white/[.04]" /><div className="h-80 rounded-[1.7rem] bg-white/[.04]" /></div></section>; }
function formatDate(value?: string) { if (!value) return "Timestamp unavailable"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", year: "numeric" }).format(date); }
function toMarkdown(report: ReturnType<typeof analyzeIdentity>) { return `# TrustDNA AI Analyst\n\nGenerated: ${report.generatedAt}\n\n## Executive Summary\n${report.executiveSummary}\n\n## Strengths\n${report.strengths.map((item) => `- ${item.title}: ${item.detail}`).join("\n") || "- No recurring evidence yet."}\n\n## Evidence Gaps\n${report.gaps.map((item) => `- ${item.title}: ${item.detail}`).join("\n") || "- None returned."}\n\n## Recommendations\n${report.recommendations.map((item) => `### ${item.title}\n- Identity Evidence: ${item.identityEvidence.join("; ") || "None"}\n- General Advice: ${item.generalAdvice}\n- Unknowns: ${item.unknowns.join("; ")}`).join("\n\n")}`; }
